// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SelfBet.Infrastructure.Persistence;

#nullable disable

namespace SelfBet.Infrastructure.Migrations
{
    [DbContext(typeof(SelfBetDbContext))]
    [Migration("20260427124158_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SelfBet.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("SelfBet.Domain.Entities.BankrollSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Note")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("StakePerSlip")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("BankrollSnapshots");
                });

            modelBuilder.Entity("SelfBet.Domain.Entities.CalibrationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Intercept")
                        .HasColumnType("double precision");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("PublishThreshold")
                        .HasColumnType("double precision");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer");

                    b.Property<double>("Slope")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Market")
                        .IsUnique();

                    b.ToTable("CalibrationProfiles");
                });

            modelBuilder.Entity("SelfBet.Domain.Entities.ForecastObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BookOdds")
                        .HasColumnType("numeric");

                    b.Property<bool>("Correct")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("ModelProbability")
                        .HasColumnType("numeric");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SlipLegId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Market", "ResolvedAtUtc");

                    b.ToTable("ForecastObservations");
                });

            modelBuilder.Entity("SelfBet.Domain.Entities.PlacementAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AttemptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BookingCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BookingUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Error")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("EvidencePath")
                        .HasColumnType("text");

                    b.Property<string>("ExternalTicketId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PlacementMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("SlipId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("PlacementAttempts");
                });

            modelBuilder.Entity("SelfBet.Domain.Entities.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CandidatesGenerated")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FixturesEvaluated")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("SlipsBuilt")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("SelfBet.Domain.Entities.Slip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BookingCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BookingUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalTicketId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<decimal>("Payout")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("PlacedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("RunDate")
                        .HasColumnType("date");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SettledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Stake")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalOdds")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Slips");
                });

            modelBuilder.Entity("SelfBet.Domain.Entities.SlipLeg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("KickoffUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("MatchTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("ModelProbability")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Odds")
                        .HasColumnType("numeric");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SlipId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SlipId");

                    b.ToTable("SlipLegs");
                });

            modelBuilder.Entity("SelfBet.Domain.Entities.StrategyConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedMarketsCsv")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("AutomationEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("EnabledLeaguesCsv")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<decimal>("MaxLegOdds")
                        .HasColumnType("numeric");

                    b.Property<int>("MaxLegsPerSlip")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinEdgeThreshold")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinLegOdds")
                        .HasColumnType("numeric");

                    b.Property<int>("MinLegsPerSlip")
                        .HasColumnType("integer");

                    b.Property<decimal>("OddsRangeMax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OddsRangeMin")
                        .HasColumnType("numeric");

                    b.Property<bool>("RequireConfirmationOnRisk")
                        .HasColumnType("boolean");

                    b.Property<int>("SlipsPerDay")
                        .HasColumnType("integer");

                    b.Property<decimal>("StakeIncrement")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StakePercentagePerSlip")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("StrategyConfigs");
                });

            modelBuilder.Entity("SelfBet.Domain.Entities.SlipLeg", b =>
                {
                    b.HasOne("SelfBet.Domain.Entities.Slip", null)
                        .WithMany("Legs")
                        .HasForeignKey("SlipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SelfBet.Domain.Entities.Slip", b =>
                {
                    b.Navigation("Legs");
                });
#pragma warning restore 612, 618
        }
    }
}
