// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SelfBet.Infrastructure.Persistence;

#nullable disable

namespace SelfBet.Infrastructure.Migrations
{
    // The full target-model snapshot lives in SelfBetDbContextModelSnapshot.cs.
    // Runtime migration application only needs the [Migration] attribute on the
    // partial class declared in 20260427190000_HistoricalDataAndTeamStrength.cs.
}
